### ISSUE TITLE
04-2 예제 오류

### ISSUE THREAD

**Issue by pcsopcso** [joshua1988/doit-vuejs#3]
공부 하던중 vuejs 예제 04-2번 예제가 브라우저에 표시가 되지 않습니다.
크롬과 사파리 둘다 제대로 표현되지가 않네요 어디가 잘못 된 건지 모르겠습니다.
예정 수정 좀 부탁 드립니다.

**Comment by joshua1988** [comment]
@pcsopcso - 안녕하세요. 파일 실행 후 url 끝에 'user'를 입력했는데 아무것도 안 뜨시나요? 
4장 2번 예제는 네스티드 라우터 관련 예제라 브라우저 주소창 끝에 'user/posts/' 와 'user/profile' 을 입력하여 비교해보셔야 합니다.

**Comment by pcsopcso** [comment]
아 네 해보니까 되네요 제가 주소를 잘못 넣어서 그랬네요 감사합니다.

**Comment by rlarnfktkd1** [comment]
파일을 찾을 수 없다고 나옵니다.

**Comment by liks79** [comment]
안녕하세요. 저자님.
좋은 책 잘보고 있습니다.
저도 마찬가지로 /user/posts, /user/profile 호출할때에 오류가 납니다.

/exam/04/04-2/index.html/user/profile
/exam/04/04-2/index.html/user/posts

아래는 오류 메시지 입니다.

Your file was not found It may have been moved or deleted.
ERR_FILE_NOT_FOUND
