### ISSUE TITLE
Vue.js 입문 도서 오탈자

### ISSUE THREAD

**Issue by seoyeongeun** [joshua1988/doit-vuejs#5]
오늘 도서를 구입해서 차근차근 보면서 하고 있습니다. (github 소스 등 X)
도서 내용 중 55P에 doit-vuejs/exam/03/03-4/index.html에서 

`new Vue({
    		el: '#app' 
    		components: {
    			'my-local-component': cmp
    		}
    	});
`

이렇게 인쇄되어있는데 '#app' 뒤에 , (콤마)가 빠져있네요~ :)

**Comment by joshua1988** [comment]
@seoyeongeun - 안녕하세요 서영은님, 오탈자 제보해주셔서 감사합니다 :) 개정판에서 수정하도록 하겠습니다! :)
